In [8]:
 #Python script that opens a file in read mode and prints its contents

import pandas as pd
pd.read_table (r"C:\Users\USER\Documents\joyouss.txt")

Empty DataFrame
Columns: [Hello, Data Analysis!]
Index: []

In [9]:
#Create a Python script that writes the string "Hello, Data Analysis!" to a new text file.

with open ( r"C:\Users\USER\Documents\joyouss.txt" , 'w') as file:
    file.write ("Hello, Data Analysis!")
print ( "Written successfully")
           

Written successfully


In [25]:
#Use the “csv” module to read the Titanic dataset. Print the first 5 rows of the dataset
import pandas as pd
df = pd.read_csv (r"C:\Users\USER\Downloads\TDI python week3 dataset(Titanic Analysis).csv" )
df.head(10)

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   
5       1         1                              Anderson, Mr. Harry    male   
6       1         1                Andrews, Miss. Kornelia Theodosia  female   
7       1         0                           Andrews, Mr. Thomas Jr    male   
8       1         1    Appleton, Mrs. Edward Dale (Charlotte Lamson)  female   
9       1         0                          Artagaveytia, Mr. Ramon    male   

       age  sibsp  parch    ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0     24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2    113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2    113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2    113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2    113781  151.5500  C22 C26        S  NaN    NaN   
5  48.0000      0      0     19952   26.5500      E12        S    3    NaN   
6  63.0000      1      0     13502   77.9583       D7        S   10    NaN   
7  39.0000      0      0    112050    0.0000      A36        S  NaN    NaN   
8  53.0000      2      0     11769   51.4792     C101        S    D    NaN   
9  71.0000      0      0  PC 17609   49.5042      NaN        C  NaN   22.0   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON  
5                     New York, NY  
6                       Hudson, NY  
7                      Belfast, NI  
8              Bayside, Queens, NY  
9              Montevideo, Uruguay

In [47]:
#After reading the Titanic CSV file, count the total number of passengers
import pandas as pd
df = pd.read_csv (r"C:\Users\USER\Downloads\TDI python week3 dataset(Titanic Analysis).csv" )
name_count = len(df)
print( 'Total number of passengers:' , name_count)

Total number of passengers: 1309


In [48]:
#write a script that calculates the average fare paid by passengers
import pandas as pd
df = pd.read_csv (r"C:\UserS\USER\Downloads\TDI python week3 dataset(Titanic Analysis).csv" )
fare_average = df['fare'].mean()
print( 'average fare paid:' , fare_average)

average fare paid: 33.29547928134557


In [54]:
#Write a Python script that calculates the number of survivors per passenger class (1st, 2nd, and 3rd class).
import pandas as pd
df = pd.read_csv (r"C:\UserS\USER\Downloads\TDI python week3 dataset(Titanic Analysis).csv" )
sur_by_class = df.groupby('pclass') ['survived'].sum()
print(sur_by_class)

pclass
1    200
2    119
3    181
Name: survived, dtype: int64


In [57]:
#Import the NumPy library and create a 1D array containing the following numbers: “[10, 15, 20, 25]”. Print the array.
import numpy as np
array = np.array([10, 15, 20, 25])
print('array:', array )

array: [10 15 20 25]


In [58]:
 #multiply each element by 2 using the array
import numpy as np
array = np.array([10, 15, 20, 25])
multiplied = array * 2
print("after multiplication" , multiplied)

after multiplication [20 30 40 50]


In [60]:
, Subtract 5 from each element using the array
import numpy as np
array = np.array([10, 15, 20, 25])
subtract = array - 5
print("after multiplication" , subtract)

after multiplication [ 5 10 15 20]


In [63]:
 #Create a 2D NumPy array with shape (3, 3) using the following data: [1, 2, 3], [4, 5, 6], [7, 8, 9]]”
arr2D= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:\n", arr2D)


2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [73]:
#Convert the "Fare" column of the Titanic dataset to a NumPy array and calculate:
import pandas as pd
df = pd.read_csv (r"C:\UserS\USER\Downloads\TDI python week3 dataset(Titanic Analysis).csv" )
df = df.dropna(subset=['fare'])
fare_array = df['fare'].to_numpy()
min_fare =  fare_array.min()
max_fare =  fare_array.max()
mean_fare =  fare_array.mean()

print (f"Min fare: {min_fare}")
print (f"Min fare: {max_fare}")
print (f"Mean fare: {mean_fare}")

Min fare: 0.0
Min fare: 512.3292
Mean fare: 33.29547928134557


In [4]:
#Use array indexing to extract the first row and first column of the 2D array created earlier. Print the results
import numpy as np
arr2D= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
first_row = arr2D[0]
first_column = arr2D[:, 0]
print("First Row:", first_row)
print("First Column:", first_column)


First Row: [1 2 3]
First Column: [1 4 7]


In [10]:
#Create a NumPy array with 10 random numbers between 0 and 1. Print the array and find the maximum value.
import numpy as np
array= np.random.rand(10)
print(array)
maxarray = array.max()
print(f"max value: {maxarray}")

[0.83686281 0.70945549 0.61621402 0.24935377 0.55575923 0.64133839
 0.15041941 0.03278469 0.30265123 0.11629483]
max value: 0.8368628096641545


In [21]:
#Practice: Survivor Analysis with NumPy:
import pandas as pd
import numpy as np
df = pd.read_csv (r"C:\UserS\USER\Downloads\TDI python week3 dataset(Titanic Analysis).csv" )
survived_arr = df['survived'].to_numpy()
survived_percentage = (survived_arr.sum() / survived_arr.size) * 100
print(f"percentage: {survived_percentage}%")

percentage: 38.19709702062643%
